[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

# Redirects for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200